name = "SimpleStatics"
uuid = "755f8035-bddb-4884-b09e-b908b7adad44"
authors = ["Will <William.joseph.box@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"

[compat]
Luxor = "3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"

[targets]
test = ["Test", "Measurements"]
